---
title: Exploratory Data Analysis of Fortune 1000 Companies
author: Kevin Zolea
date: '2022-09-01'
slug: exploratory-data-analysis-of-fortune-1000-companies
categories:
  - Python
tags:
  - Python
subtitle: ''
summary: "Learn how to use Python's powerful data analysis and visualization libraries, Pandas and Seaborn, to explore the Fortune 1000 companies dataset and gain insights into the relationships between different variables."
authors: []
lastmod: '2022-09-01T16:12:33-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
# Introduction to Exploring Fortune 1000 Companies Data using Python

As a data analyst, one of the most important skills you need to have is the ability to work with data to gain insights and answer questions. Recently, my girlfriend started working for a Fortune 1000 company, which sparked my curiosity about the makeup of these companies. In particular, I was interested in the percentage of women who are CEOs, which states have the most Fortune 1000 companies, and the top profitable companies. To answer these questions, I searched for a suitable dataset on Google and found one on [Kaggle](https://www.kaggle.com/datasets/winston56/fortune-500-data-2021){target="_blank"} that had exactly what I was looking for. The dataset contained data for the year 2021, and was scraped from the [fortune website](https://fortune.com/){target="_blank"} by the dataset [author](https://www.kaggle.com/code/winston56/fortune-500-data-collection/notebook){target="_blank"}.

Before diving into the analysis, let's discuss the meaning of exploratory data analysis (EDA). EDA is a valuable process used by data scientists and analysts to investigate and analyze datasets. It helps to identify the main characteristics of the data through various visualization techniques.

To begin the analysis, I used Python, along with the ```Pandas```, ```Seaborn```, ```Squarify``, and ```Matplotlib``` libraries. Pandas was used to read in the dataset, Seaborn was used for data visualization, ```Squarify``` was used to create a treemap, and ```Matplotlib``` was used for additional data visualization.

Here's the Python code used to import the necessary libraries:
```{r setup, include=FALSE,message=FALSE,warning=FALSE, results = 'hide'}

library(reticulate)
py_install("pandas")
py_install("seaborn")
py_install("squarify")
py_install("matplotlib")


```


#### Import libraries used for analysis
```{python}
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import squarify # makes tree map
import seaborn as sns

```


#### Read in data and perform EDA

After importing the necessary libraries, I read in the dataset using the ```pandas``` library, and then checked the structure of the data and the first few rows using the following code:
```{python, echo=T, warning=F, message=F}
df = pd.read_csv("Fortune_1000.csv") # Read csv file into python

df.dtypes # see structure of data
df.head(n=10)
```


Next, I wanted to find out the percentage of women who are CEOs. To do this, I used the ```value_counts()``` method in Pandas to count the number of female and male CEOs, and then created a pie chart using Matplotlib to visualize the results:


```{python, echo=T, warning=F, message=F}
# Find out percent of woman CEOs
wf= df['ceo_woman'].value_counts(normalize=True).to_frame()
# Make pie chart of woman vs. men ceos
labels = "Male","Female"
colors = ["blue", "purple"]
plt.title("Percentage of Male Vs. Female CEOs")
plt.pie(wf["ceo_woman"],labels = labels, autopct = '%.1f%%',
        wedgeprops = {"edgecolor" : "black",
                      'linewidth': 1,
                      'antialiased': True})
                      
plt.show()
                      
```                      
From the pie chart, it's clear that only 6.8% of Fortune 1000 companies are led by female CEOs.

Next, I wanted to see which states have the most Fortune 1000 companies. I used the ```value_counts()``` method in Pandas to count the number of companies in each state, and then created a treemap using Squarify to visualize the results:

```{python, echo=F, warning=F, message=F}

# Which states have the most fortune 1000 companies
state_count = df['state'].value_counts().rename_axis('state').reset_index(name = 'counts')
# Get top 10 states with the most companies
state_count = state_count.nlargest(20,'counts')
# Make tree map to show states with most fortune 1000 companies
sizes = state_count['counts']
labels =  [f'{state}\n{count}' for state, count in zip(state_count.state, state_count.counts)]
squarify.plot(sizes = sizes, label = labels, pad=True,
              color = 'mediumblue',text_kwargs={'color':'white'})
plt.axis('off')
plt.title('Top 10 States with the most headquarters')
plt.show() 
```
This code uses pandas and squarify libraries to create a treemap that shows the top 20 states with the most Fortune 1000 companies.

First, the code creates a DataFrame 'state_count' using the value_counts() method to count the number of times each state appears in the 'state' column of the original DataFrame 'df'. The resulting DataFrame is then sorted in descending order using nlargest() function to get the top 20 states with the most companies.

The sizes and labels for the treemap are then created. The sizes variable is a list of the 'counts' column of the 'state_count' DataFrame, while the labels variable is a list comprehension that creates a string for each state and its count in the format 'state\ncount'.

Finally, the squarify library is used to create the treemap. The sizes and labels variables are passed to the squarify.plot() method, along with a color map and an alpha value to adjust the opacity of the squares. The plt.axis() method is used to turn off the x and y axis labels and the title of the plot is set using plt.title(). The resulting treemap shows the states with the most Fortune 1000 companies in a visually appealing way.

To wrap up, let's take a look at how we can compare profit and revenue in a bar plot. We can use this visual tool to gain insights into the performance of the top five Fortune 1000 companies. To achieve this, we melted the data to create a tidy format, then used Seaborn to create a clean and informative bar plot. Additionally, we created a table to show the percentage change in revenue to profit for each company.
```{python, echo=T, warning=F, message=F, results = 'hide'}
# Profit vs. revenue in bar plot
rev_prof = df.nlargest(5,'revenue')
rev_prof = pd.melt(rev_prof,id_vars = ['company'],value_vars = ['revenue','profit'])
sns.set_theme(style="whitegrid")
sns.set_color_codes("pastel")
p1 =sns.barplot(x="value", y="company",hue = "variable",data= rev_prof)
p1.set_title("Profit Vs. Revenue for Top 5 Fortune 1000 Companies")
p1.set(xlabel='Millions ($)', ylabel="")

# Make table to put next to plot to show percent change in rev to prof
df2 = df.nlargest(5,'revenue')
#define custom function
def find_change(df2):
    change = (df2['profit']/df2['revenue'])*100
    return(change)
df3 = df2.groupby('company').apply(find_change).reset_index()
df3=df3.round()
#per_change = rev_prof.groupby('company','variable','value').assign(percent_change = (''))
# Put barplot and table together in same plot

plt.subplots_adjust(left=0.2, bottom=0.4)

the_table = plt.table(cellText=df3.values,
          cellLoc = 'center', rowLoc = 'center',
          transform=plt.gcf().transFigure,
          bbox = ([0.3, 0.1, 0.5, 0.2]))
the_table.auto_set_font_size(False)
the_table.set_fontsize(6)

plt.show()

```

These are just a few examples of the many techniques available for EDA. If you want to dive deeper into this topic, I highly recommend checking out the [Python Plot Gallery](https://www.python-graph-gallery.com){target="_blank"}. It's an excellent resource to explore the vast array of visualization tools available and discover new ways to gain insights from your data.




