---
title: Exploratory Data Analysis of Fortune 1000 Companies
author: Kevin Zolea
date: '2022-09-01'
slug: exploratory-data-analysis-of-fortune-1000-companies
categories:
  - Python
tags:
  - Python
subtitle: ''
summary: ''
authors: []
lastmod: '2022-09-01T16:12:33-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
My girlfriend recently just got a new job at a Fortune 1000 company and it led me to ask many different questions. What percent of woman are CEOs? Which states have the most fortune 1000 companies? What are the top profitable companies? The list went on and on.. So I quickly went to google and tried to find a dataset that will allow me to answer some of these questions using python.

I stumbled across a great [dataset](https://www.kaggle.com/datasets/winston56/fortune-500-data-2021){target="_blank"} that had exactly what I was looking for. The author of this dataset pulled the data by scraping the [fortune website](https://fortune.com/){target="_blank"}. He goes into great detail on how he accomplished this in this [blog post](https://www.kaggle.com/code/winston56/fortune-500-data-collection/notebook){target="_blank"}. I highly recommend checking it out if you are interested in learning more. The data is for the year 2021.

Before I go into explaining how to pull the data into python and the code behind the analysis, I want to touch on what exploratory data analysis even means! Exploratory data analysis, or EDA for short, is a very useful process that data scientists/data analysts use to analyze and investigate data sets. It allows you to gain insights into the main characteristics of your data. Most times this is accomplished by employing different data visulization methods.

```{r setup, include=FALSE,message=FALSE,warning=FALSE}

library(reticulate)
py_install("pandas")
py_install("seaborn")
py_install("squarify")
py_install("matplotlib.pyplot")


```


#### Import modules used for analysis
```{python}
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import squarify # makes tree map
import seaborn as sns

```


#### Read in data and perform EDA

 The ```pandas``` package can be used to read in cvs files. After the data is read into python, it's always best to view the structure of your data and view the first few rows.

```{python, echo=F, warning=F, message=F, results = 'hide'}
df = pd.read_csv("Fortune_1000.csv") # Read csv file into python

df.dtypes # see structure of data
df.head(n=10)
```


My first question to answer is how many woman are CEOs. I was quickly able to see this by making a pie chart. As you can see from the chart, there are only 6.8% woman CEOs. 

```{python, echo=F, warning=F, message=F, results = 'hide'}
# Find out percent of woman CEOs
wf= df['ceo_woman'].value_counts(normalize=True).to_frame()
# Make pie chart of woman vs. men ceos
labels = "Male","Female"
plt.title("Percentage of Male Vs. Female CEOs")
plt.pie(wf["ceo_woman"],labels = labels, autopct = '%.1f%%',
        wedgeprops = {"edgecolor" : "black",
                      'linewidth': 1,
                      'antialiased': True})
                      
plt.show()
                      
```                      

Next, lets see which states have the most companies. I will use a treemap to show this. Although this probably isn't the best chart to show this I thought it seemed pretty cool. California came out on top with 121.

```{python, echo=F, warning=F, message=F, results = 'hide'}

# Which states have the most fortune 1000 companies
state_count = df['state'].value_counts().rename_axis('state').reset_index(name = 'counts')
# Get top 10 states with the most companies
state_count = state_count.nlargest(20,'counts')
# Make tree map to show states with most fortune 1000 companies
sizes = state_count['counts']
labels =  [f'{state}\n{count}' for state, count in zip(state_count.state, state_count.counts)]
squarify.plot(sizes = sizes, label = labels, pad=True,
              color = 'mediumblue',text_kwargs={'color':'white'})
plt.axis('off')
plt.title('Top 10 States with the most headquarters')
plt.show() 
```


```{python}
#Which sectors have the most fortune 1000 companies
sector_count =  df['sector'].value_counts().rename_axis('sector').reset_index(name = 'counts')
```

```{python}
# Is there a relationship between # of employees and revenue?
sns.lmplot(x="revenue",y="num. of employees",
           data=df)

plt.show()
```           
           
```{python, echo=F, warning=F, message=F, results = 'hide'}
# Profit vs. revenue in bar plot
rev_prof = df.nlargest(5,'revenue')
rev_prof = pd.melt(rev_prof,id_vars = ['company'],value_vars = ['revenue','profit'])
sns.set_theme(style="whitegrid")
sns.set_color_codes("pastel")
p1 =sns.barplot(x="value", y="company",hue = "variable",data= rev_prof)
p1.set_title("Profit Vs. Revenue for Top 5 Fortune 1000 Companies")
p1.set(xlabel='Millions ($)', ylabel="")

# Make table to put next to plot to show percent change in rev to prof
df2 = df.nlargest(5,'revenue')
#define custom function
def find_change(df2):
    change = (df2['profit']/df2['revenue'])*100
    return(change)
df3 = df2.groupby('company').apply(find_change).reset_index()
df3=df3.round()
#per_change = rev_prof.groupby('company','variable','value').assign(percent_change = (''))
# Put barplot and table together in same plot

plt.subplots_adjust(left=0.2, bottom=0.4)

the_table = plt.table(cellText=df3.values,
          cellLoc = 'center', rowLoc = 'center',
          transform=plt.gcf().transFigure,
          bbox = ([0.3, 0.1, 0.5, 0.2]))
the_table.auto_set_font_size(False)
the_table.set_fontsize(6)

plt.show()
```


